### ISSUE TITLE
multiball_locks is only valid in mode configs

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-docs#109]
From @Wolfmarsh:

When trying to define multiball_locks in the machine config, you get the following error: "Found a "multiball_locks:" section in config file C:\spaceballs\config\multiballs.yaml, but that section is not valid in machine config files."

According to the docs at http://docs.missionpinball.org/en/latest/config/multiball_locks.html it is valid in machine configs.

**Comment by jabdoa2** [comment]
I think this is only valid in 0.50/dev

**Comment by jabdoa2** [comment]
fixed in 0.50
