### ISSUE TITLE
Update slide_frame documentation

### ISSUE THREAD

**Issue by unRARed** [missionpinball/mpf-docs#140]
```
ValueError: "slide_frame" is not a valid MPF display widget type.
```

Per [this refactor](https://github.com/missionpinball/mpf-mc/issues/186), it would appear `slide_frame` [has been replaced](http://docs.missionpinball.org/en/dev/displays/widgets/slide_frame/index.html?highlight=slide_frame) in v0.50.

**Comment by jabdoa2** [comment]
fixed in 0.50 docs
