### ISSUE TITLE
Show files: case sensitivity example is confusing

### ISSUE THREAD

**Issue by murrphy** [missionpinball/mpf-docs#142]
In file_shows.rst the example provided to demonstrate that MPF is case insensitive is incorrect and could be misinterpreted by the reader.  The example provided compares 'YouShow.yaml' and 'yourshow.yaml'.  The first example should be 'YourShow.yaml', the 'r' in your is missing.

**Comment by jabdoa2** [comment]
Good point. This recently changed in MPF dev/0.50. We probably need to change it in a few places

**Comment by jabdoa2** [comment]
removed that section in https://github.com/missionpinball/mpf-docs/commit/d0c470eaf34040c3c1070a4acea3d046ed924109
