### ISSUE TITLE
Docs not displaying correctly in Chrome on Android

### ISSUE THREAD

**Issue by qcapen** [missionpinball/mpf-docs#18]
There is some kind of layout/CSS error/incompatibility in Chrome on Android that causes the majority of the page to be off the left side of the screen and no ability to scroll to see it.  It makes it almost impossible to navigate to any other page and not possible to read the content.  Working fine in Chrome on my desktop.  I hate finding and fixing these device compatibility issues!

Screenshot attached:
![screenshot_20160604-095008](https://cloud.githubusercontent.com/assets/12347597/15800930/97ad711c-2a43-11e6-9d8a-d085aa23cdb2.png)

Chrome 50.0.2661.89 on Android 6.0.1

**Comment by HarryXS** [comment]
Seems to be the same for all webkit browsers on smartphones (tablets not tested). Safari renders the same wrong way on ios.

**Comment by toomanybrians** [comment]
closed since we moved to RTD
