### ISSUE TITLE
Install to virtualenv instead of system?

### ISSUE THREAD

**Issue by bowilliams** [missionpinball/mpf-docs#247]
The instructions for installing pypinproc 2.1 (http://docs.missionpinball.org/en/latest/hardware/multimorphic/mac.html) direct users to a system install. Given that the tutorial has you set up a virtualenv, makes more sense to install there, yeah?

**Comment by jabdoa2** [comment]
Yes makes sense. Different people wrote different tutorials. Some use virtualenvs. Others don't. Feel free to add a note here if you want.

**Comment by jabdoa2** [comment]
fixed by #248
