### ISSUE TITLE
Raspberry Pi install video test throws error

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf-docs#33]
@HarryXS Not sure what this problem might be, but when I follow the steps to test that video works in the RPi install instructions, I get a Kivy error that says it's looking for mpf_video_small_test.png even though I typed in mpf_video_small_test.mp4. The player still appears, but no video plays.

I've attached a screenshot. I ran it directly from the tests/machine_files/video/videos folder in this example, but I tried the full command as you wrote in the instructions, too.
<img width="579" alt="messages image 1146790575" src="https://cloud.githubusercontent.com/assets/11875962/18373298/8bea9ce0-7608-11e6-8d4e-df0ae9695abb.png">

By the way - nice find with KivyPie. I'm very hopeful that this will work!

**Comment by jabdoa2** [comment]
no longer valid
