### ISSUE TITLE
Widget documentation

### ISSUE THREAD

**Issue by jrobert2** [missionpinball/mpf-docs#42]
Widgets documentations look complete (for example: http://docs.missionpinball.org/en/stable/displays/widgets/widget/image.html ) but some (most ?) pages are  actually "only" the part inherited from the common widget. It has been quite confusing to me.

What about adding an information about that fact (like "inhereted from common" ) or removing the duplicated doc and giving a link to it ?

**Comment by jabdoa2** [comment]
fixed
