### ISSUE TITLE
Link to macos installer broken

### ISSUE THREAD

**Issue by jrobert2** [missionpinball/mpf-docs#45]
The link to the macos installer on the page http://mpf.readthedocs.io/en/stable/install/mac.html is broken (link to https://missionpinball.com/Mission%20Pinball%20Framework.dmg)

**Comment by toomanybrians** [comment]
Whoops. The new link (for the time being) is: https://dl.dropboxusercontent.com/u/51030/Mission%20Pinball%20Framework.dmg

I just fixed the docs too.
