### ISSUE TITLE
Expand the explanation on COM ports

### ISSUE THREAD

**Issue by jeremytedwards** [missionpinball/mpf-docs#50]
Are there differences between Mac an PC?
Can some definitions be added for what each COM port refers to?

```
# ports for PC
ports: com3, com4, com5 

# ports for MAC
ports: /dev/tty.usbserial-1413B, /dev/tty.usbserial-1413C 
```

reference page:
http://docs.missionpinball.org/en/0.30/hardware/configuring_fast_hardware.html

**Comment by jabdoa2** [comment]
done in the relevant places
