### ISSUE TITLE
Document Config Format per Platform

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-docs#53]
For all platforms, document and link number formats for
- switches
- matrix_lights
- coils
- leds

P-Roc (switches, leds, coils, matrix_lights):
a) WPC syntax
b) Custom; direct and matrix switches; lamp matrix
c) PDB syntax (optional)
P3-Roc (switches, leds, coils, matrix_lights):
a) PDB syntax
Snux (coils, switches):
Fast (switches, leds, coils, matrix_lights):
a) WPC
b) PDB syntax / fast syntax
OPP (switches, leds, coils, matrix_lights):
Fadecandy (leds):

Probably good to break out PDB and WPC (Partly here: http://docs.missionpinball.org/en/stable/machines/wpc.html) config styles.

**Comment by toomanybrians** [comment]
done
