### ISSUE TITLE
PDF needs a custom title page

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-docs#62]
Lots of research and I can't figure out how to do this, so I'm posting it here so I can remember to come back and look at it some other time. I want to add a few things:

* Logo
* Version of MPF that the PDF is for
* Note that the PDF is formatted for the screen, but we can generate versions for suitable for printing if people want them.

**Comment by FinestArcadeArt** [comment]
Hi,
I have adobe acrobat x pro and with that installed I can export Microsoft word documents as PDF files. 
I don't know if this helps.

**Comment by jabdoa2** [comment]
This issue is for our auto generated pdf version of the docs. I guess that the pdf is generated by sphinx and needs to be configured there somehow.
